import type { AdminDb } from "./types";

export const SEED_VEHICLE_MODELS = [
  "Corolla",
  "Civic",
  "HiAce",
  "Fortuner",
  "City",
  "Revo",
] as const;

export function seedDb(): AdminDb {
  const now = new Date().toISOString();
  return {
    fuel_price_pkr: 280.5,
    shuttle_drivers: [
      {
        id: "sd_1",
        full_name: "Shuttle Driver 1",
        username: "shuttle.driver1",
        password: "shuttle-001",
        vehicle_id: "veh_2",
        is_active: true,
        created_at: now,
      },
    ],
    chauffeur_driver_signups: [
      {
        id: "cds_1",
        full_name: "Bilal Khan",
        phone: "+92 300 1111111",
        cnic: "42101-1234567-1",
        license_no: "LIC-7788",
        vehicle_make: "Toyota",
        vehicle_model: "Corolla",
        vehicle_year: 2021,
        plate_no: "KHI-555",
        status: "pending",
        created_at: now,
      },
      {
        id: "cds_2",
        full_name: "Sara Iqbal",
        phone: "+92 300 2222222",
        cnic: "35202-7654321-9",
        license_no: "LIC-1122",
        vehicle_make: "Honda",
        vehicle_model: "Civic",
        vehicle_year: 2020,
        plate_no: "LHR-909",
        status: "pending",
        created_at: now,
      },
    ],
    shuttle_routes: [
      {
        id: "rt_1",
        name: "Clifton to Tower",
        polyline_mock: "mock-polyline",
        stops: [
          { id: "st_1", name: "Clifton", eta_minutes_from_start: 0 },
          { id: "st_2", name: "NIPA", eta_minutes_from_start: 25 },
          { id: "st_3", name: "Tower (Office)", eta_minutes_from_start: 55 },
        ],
        company_id: "cmp_1",
        driver_id: "sd_1",
        vehicle_id: "veh_2",
        created_at: now,
        updated_at: now,
      },
    ],
    chauffeur_cars: [
      {
        id: "car_1",
        driver_name: "Imran Driver",
        model: "Corolla",
        plate_no: "KHI-121",
        status: "available",
        last_seen_at: now,
      },
      {
        id: "car_2",
        driver_name: "Danish Driver",
        model: "Civic",
        plate_no: "LHR-777",
        status: "in_trip",
        last_seen_at: now,
      },
    ],
    chauffeur_bookings: [],
    chauffeur_contracts: [
      {
        id: "cc_1",
        company_id: "cmp_1",
        base_fuel_price_pkr: 260,
        contract_pct: 0.2,
        overtime_rate_per_hour: 800,
        outstation_allowance_per_day: 2500,
        driver_accommodation_per_night: 3000,
        is_auto_revision_enabled: true,
        base_rates: [
          { model: "Corolla", rate_5hr: 6000, rate_10hr: 9000, rate_24hr: 15000, monthly_10hr: 180000, monthly_24hr: 260000 },
          { model: "Fortuner", rate_5hr: 9000, rate_10hr: 14000, rate_24hr: 22000, monthly_10hr: 260000, monthly_24hr: 360000 },
        ],
        created_at: now,
        updated_at: now,
      },
    ],
    shuttle_asset_pricing: [
      {
        id: "sap_1",
        company_id: "cmp_1",
        vehicle_id: "veh_2",
        fixed_monthly_amount_pkr: 150000,
        created_at: now,
        updated_at: now,
      },
    ],
    updated_at: now,
    vehicles: [
      {
        id: "veh_1",
        plate_no: "ABC-123",
        make: "Toyota",
        model: "Corolla",
        year: 2022,
        color: "White",
        ownership: "owned",
        fuel_avg_in_city_km_per_l: 12,
        fuel_avg_out_station_km_per_l: 15,
        is_active: true,
      },
      {
        id: "veh_2",
        plate_no: "KHI-808",
        make: "Toyota",
        model: "HiAce",
        year: 2020,
        color: "Silver",
        ownership: "partner",
        fuel_avg_in_city_km_per_l: 8,
        fuel_avg_out_station_km_per_l: 10,
        is_active: true,
      },
    ],
    companies: [
      {
        id: "cmp_1",
        name: "Acme Textiles",
        address: "Karachi, Sindh",
        ntn: "1234567-8",
        contact_person: "Ayesha Khan",
        email: "ops@acme.example",
        services_enabled: { shuttle_enabled: true, chauffeur_enabled: true },
        allowed_vehicle_models: ["Corolla", "Fortuner"],
        employees: [
          {
            id: "emp_1",
            full_name: "Ali Raza",
            phone: "+92 300 0000001",
            email: "ali@acme.example",
            employee_id: "ACME-001",
            route_id: "R-12",
            status: "active",
            username: "ali.raza",
            password: "pass-001",
          },
          {
            id: "emp_2",
            full_name: "Hira Noor",
            phone: "+92 300 0000002",
            email: "hira@acme.example",
            employee_id: "ACME-002",
            status: "active",
            username: "hira.noor",
            password: "pass-002",
          },
        ],
        created_at: now,
      },
      {
        id: "cmp_2",
        name: "BluePeak BPO",
        address: "Lahore, Punjab",
        ntn: "9876543-2",
        contact_person: "Saad Ahmed",
        email: "admin@bluepeak.example",
        services_enabled: { shuttle_enabled: false, chauffeur_enabled: true },
        allowed_vehicle_models: ["Civic", "City"],
        employees: [],
        created_at: now,
      },
    ],
  };
}


