// import type { AdminDb } from "./types";

// export const SEED_VEHICLE_MODELS = [
//   "Corolla",
//   "Civic",
//   "HiAce",
//   "Fortuner",
//   "City",
//   "Revo",
// ] as const;

// export function seedDb(): AdminDb {
//   const now = new Date().toISOString();
//   return {
//     fuel_price_pkr: 280.5,
//     shuttle_drivers: [
//       {
//         id: "sd_1",
//         full_name: "Shuttle Driver 1",
//         username: "shuttle.driver1",
//         password: "shuttle-001",
//         vehicle_id: "veh_2",
//         is_active: true,
//         created_at: now,
//       },
//     ],
//     chauffeur_driver_signups: [
//       {
//         id: "cds_1",
//         full_name: "Bilal Khan",
//         phone: "+92 300 1111111",
//         cnic: "42101-1234567-1",
//         license_no: "LIC-7788",
//         vehicle_make: "Toyota",
//         vehicle_model: "Corolla",
//         vehicle_year: 2021,
//         plate_no: "KHI-555",
//         status: "pending",
//         created_at: now,
//       },
//       {
//         id: "cds_2",
//         full_name: "Sara Iqbal",
//         phone: "+92 300 2222222",
//         cnic: "35202-7654321-9",
//         license_no: "LIC-1122",
//         vehicle_make: "Honda",
//         vehicle_model: "Civic",
//         vehicle_year: 2020,
//         plate_no: "LHR-909",
//         status: "pending",
//         created_at: now,
//       },
//     ],
//     shuttle_routes: [
//       {
//         id: "rt_1",
//         name: "Clifton to Tower",
//         polyline_mock: "mock-polyline",
//         stops: [
//           { id: "st_1", name: "Clifton", eta_minutes_from_start: 0 },
//           { id: "st_2", name: "NIPA", eta_minutes_from_start: 25 },
//           { id: "st_3", name: "Tower (Office)", eta_minutes_from_start: 55 },
//         ],
//         company_id: "cmp_1",
//         driver_id: "sd_1",
//         vehicle_id: "veh_2",
//         created_at: now,
//         updated_at: now,
//       },
//     ],
//     chauffeur_cars: [
//       {
//         id: "car_1",
//         driver_name: "Imran Driver",
//         model: "Corolla",
//         plate_no: "KHI-121",
//         status: "available",
//         last_seen_at: now,
//         lat: 24.8607, // Karachi - Clifton area
//         lng: 67.0011,
//       },
//       {
//         id: "car_2",
//         driver_name: "Danish Driver",
//         model: "Civic",
//         plate_no: "LHR-777",
//         status: "in_trip",
//         last_seen_at: now,
//         lat: 24.9000, // Karachi - DHA area
//         lng: 67.0500,
//       },
//       {
//         id: "car_3",
//         driver_name: "Ahmed Ali",
//         model: "Fortuner",
//         plate_no: "KHI-999",
//         status: "in_trip", // In trip for the active booking
//         last_seen_at: now,
//         lat: 24.8700, // Current location between pickup and dropoff in Karachi
//         lng: 67.0400,
//       },
//       {
//         id: "car_4",
//         driver_name: "Hassan Raza",
//         model: "Corolla",
//         plate_no: "KHI-456",
//         status: "offline",
//         last_seen_at: now,
//         lat: 24.8400, // Karachi - Saddar area
//         lng: 66.9800,
//       },
//     ],
//     chauffeur_bookings: [
//       {
//         id: "bk_1",
//         company_id: "cmp_1",
//         passenger_employee_id: "emp_1",
//         vehicle_model: "Corolla",
//         trip_type: "in_city",
//         package: "10hr",
//         scheduled_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2 hours from now
//         status: "pending",
//         pickup_address: "Clifton Block 9, Karachi",
//         pickup_lat: 24.8000,
//         pickup_lng: 67.0300,
//         dropoff_address: "I.I. Chundrigar Road, Karachi",
//         dropoff_lat: 24.8500,
//         dropoff_lng: 67.0000,
//         created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 minutes ago
//         updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
//       },
//       {
//         id: "bk_2",
//         company_id: "cmp_1",
//         passenger_employee_id: "emp_2",
//         vehicle_model: "Fortuner",
//         trip_type: "out_station",
//         package: "24hr",
//         scheduled_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
//         status: "in_progress",
//         driver_car_id: "car_3",
//         driver_name: "Ahmed Ali",
//         driver_phone: "+92 300 3333333",
//         plate_no: "KHI-999",
//         approved_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
//         approved_by: "superadmin",
//         pickup_address: "DHA Phase 5, Karachi",
//         pickup_lat: 24.8200,
//         pickup_lng: 67.0700,
//         dropoff_address: "Jinnah International Airport, Karachi",
//         dropoff_lat: 24.9065,
//         dropoff_lng: 67.1606,
//         created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
//         updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
//       },
//       // Completed bookings for reports (current month)
//       {
//         id: "bk_3",
//         company_id: "cmp_1",
//         passenger_employee_id: "emp_1",
//         vehicle_model: "Corolla",
//         trip_type: "in_city",
//         package: "10hr",
//         scheduled_at: new Date(new Date().getFullYear(), new Date().getMonth(), 5, 9, 0).toISOString(),
//         status: "completed",
//         driver_car_id: "car_1",
//         driver_name: "Imran Driver",
//         driver_phone: "+92 300 4444444",
//         plate_no: "KHI-121",
//         approved_at: new Date(new Date().getFullYear(), new Date().getMonth(), 5, 8, 30).toISOString(),
//         approved_by: "superadmin",
//         pickup_address: "Clifton Block 9, Karachi",
//         pickup_lat: 24.8000,
//         pickup_lng: 67.0300,
//         dropoff_address: "I.I. Chundrigar Road, Karachi",
//         dropoff_lat: 24.8500,
//         dropoff_lng: 67.0000,
//         created_at: new Date(new Date().getFullYear(), new Date().getMonth(), 5, 8, 0).toISOString(),
//         updated_at: new Date(new Date().getFullYear(), new Date().getMonth(), 5, 19, 0).toISOString(),
//       },
//       {
//         id: "bk_4",
//         company_id: "cmp_1",
//         passenger_employee_id: "emp_2",
//         vehicle_model: "Fortuner",
//         trip_type: "out_station",
//         package: "24hr",
//         scheduled_at: new Date(new Date().getFullYear(), new Date().getMonth(), 8, 6, 0).toISOString(),
//         status: "completed",
//         driver_car_id: "car_3",
//         driver_name: "Ahmed Ali",
//         driver_phone: "+92 300 3333333",
//         plate_no: "KHI-999",
//         approved_at: new Date(new Date().getFullYear(), new Date().getMonth(), 8, 5, 30).toISOString(),
//         approved_by: "superadmin",
//         pickup_address: "DHA Phase 5, Karachi",
//         pickup_lat: 24.8200,
//         pickup_lng: 67.0700,
//         dropoff_address: "Jinnah International Airport, Karachi",
//         dropoff_lat: 24.9065,
//         dropoff_lng: 67.1606,
//         created_at: new Date(new Date().getFullYear(), new Date().getMonth(), 7, 20, 0).toISOString(),
//         updated_at: new Date(new Date().getFullYear(), new Date().getMonth(), 9, 6, 0).toISOString(),
//       },
//       {
//         id: "bk_5",
//         company_id: "cmp_1",
//         passenger_employee_id: "emp_1",
//         vehicle_model: "Corolla",
//         trip_type: "in_city",
//         package: "5hr",
//         scheduled_at: new Date(new Date().getFullYear(), new Date().getMonth(), 12, 14, 0).toISOString(),
//         status: "completed",
//         driver_car_id: "car_1",
//         driver_name: "Imran Driver",
//         driver_phone: "+92 300 4444444",
//         plate_no: "KHI-121",
//         approved_at: new Date(new Date().getFullYear(), new Date().getMonth(), 12, 13, 45).toISOString(),
//         approved_by: "superadmin",
//         pickup_address: "Tower, Karachi",
//         pickup_lat: 24.8500,
//         pickup_lng: 67.0000,
//         dropoff_address: "Gulshan-e-Iqbal, Karachi",
//         dropoff_lat: 24.9200,
//         dropoff_lng: 67.0800,
//         created_at: new Date(new Date().getFullYear(), new Date().getMonth(), 12, 13, 0).toISOString(),
//         updated_at: new Date(new Date().getFullYear(), new Date().getMonth(), 12, 19, 0).toISOString(),
//       },
//       {
//         id: "bk_6",
//         company_id: "cmp_1",
//         passenger_employee_id: "emp_2",
//         vehicle_model: "Fortuner",
//         trip_type: "in_city",
//         package: "10hr",
//         scheduled_at: new Date(new Date().getFullYear(), new Date().getMonth(), 15, 8, 0).toISOString(),
//         status: "completed",
//         driver_car_id: "car_3",
//         driver_name: "Ahmed Ali",
//         driver_phone: "+92 300 3333333",
//         plate_no: "KHI-999",
//         approved_at: new Date(new Date().getFullYear(), new Date().getMonth(), 15, 7, 30).toISOString(),
//         approved_by: "superadmin",
//         pickup_address: "Clifton, Karachi",
//         pickup_lat: 24.8000,
//         pickup_lng: 67.0300,
//         dropoff_address: "DHA Phase 5, Karachi",
//         dropoff_lat: 24.8200,
//         dropoff_lng: 67.0700,
//         created_at: new Date(new Date().getFullYear(), new Date().getMonth(), 14, 18, 0).toISOString(),
//         updated_at: new Date(new Date().getFullYear(), new Date().getMonth(), 15, 18, 0).toISOString(),
//       },
//       {
//         id: "bk_7",
//         company_id: "cmp_1",
//         passenger_employee_id: "emp_1",
//         vehicle_model: "Corolla",
//         trip_type: "out_station",
//         package: "24hr",
//         scheduled_at: new Date(new Date().getFullYear(), new Date().getMonth(), 20, 7, 0).toISOString(),
//         status: "completed",
//         driver_car_id: "car_1",
//         driver_name: "Imran Driver",
//         driver_phone: "+92 300 4444444",
//         plate_no: "KHI-121",
//         approved_at: new Date(new Date().getFullYear(), new Date().getMonth(), 20, 6, 30).toISOString(),
//         approved_by: "superadmin",
//         pickup_address: "Karachi Airport",
//         pickup_lat: 24.9065,
//         pickup_lng: 67.1606,
//         dropoff_address: "Lahore Airport",
//         dropoff_lat: 31.5204,
//         dropoff_lng: 74.3587,
//         created_at: new Date(new Date().getFullYear(), new Date().getMonth(), 19, 20, 0).toISOString(),
//         updated_at: new Date(new Date().getFullYear(), new Date().getMonth(), 21, 7, 0).toISOString(),
//       },
//     ],
//     chauffeur_contracts: [
//       {
//         id: "cc_1",
//         company_id: "cmp_1",
//         base_fuel_price_pkr: 260,
//         contract_pct: 0.2,
//         overtime_rate_per_hour: 800,
//         outstation_allowance_per_day: 2500,
//         driver_accommodation_per_night: 3000,
//         is_auto_revision_enabled: true,
//         base_rates: [
//           { model: "Corolla", rate_5hr: 6000, rate_10hr: 9000, rate_24hr: 15000, monthly_10hr: 180000, monthly_24hr: 260000 },
//           { model: "Fortuner", rate_5hr: 9000, rate_10hr: 14000, rate_24hr: 22000, monthly_10hr: 260000, monthly_24hr: 360000 },
//         ],
//         created_at: now,
//         updated_at: now,
//       },
//     ],
//     shuttle_asset_pricing: [
//       {
//         id: "sap_1",
//         company_id: "cmp_1",
//         vehicle_id: "veh_2",
//         fixed_monthly_amount_pkr: 150000,
//         created_at: now,
//         updated_at: now,
//       },
//     ],
//     updated_at: now,
//     vehicles: [
//       {
//         id: "veh_1",
//         plate_no: "ABC-123",
//         make: "Toyota",
//         model: "Corolla",
//         year: 2022,
//         color: "White",
//         ownership: "owned",
//         fuel_avg_in_city_km_per_l: 12,
//         fuel_avg_out_station_km_per_l: 15,
//         is_active: true,
//       },
//       {
//         id: "veh_2",
//         plate_no: "KHI-808",
//         make: "Toyota",
//         model: "HiAce",
//         year: 2020,
//         color: "Silver",
//         ownership: "partner",
//         fuel_avg_in_city_km_per_l: 8,
//         fuel_avg_out_station_km_per_l: 10,
//         is_active: true,
//       },
//     ],
//     companies: [
//       {
//         id: "cmp_1",
//         name: "Acme Textiles",
//         address: "Karachi, Sindh",
//         ntn: "1234567-8",
//         contact_person: "Ayesha Khan",
//         email: "ops@acme.example",
//         services_enabled: { shuttle_enabled: true, chauffeur_enabled: true },
//         allowed_vehicle_models: ["Corolla", "Fortuner"],
//         employees: [
//           {
//             id: "emp_1",
//             full_name: "Ali Raza",
//             phone: "+92 300 0000001",
//             email: "ali@acme.example",
//             employee_id: "ACME-001",
//             route_id: "R-12",
//             status: "active",
//             username: "ali.raza",
//             password: "pass-001",
//           },
//           {
//             id: "emp_2",
//             full_name: "Hira Noor",
//             phone: "+92 300 0000002",
//             email: "hira@acme.example",
//             employee_id: "ACME-002",
//             status: "active",
//             username: "hira.noor",
//             password: "pass-002",
//           },
//         ],
//         created_at: now,
//       },
//       {
//         id: "cmp_2",
//         name: "BluePeak BPO",
//         address: "Karachi, Sindh",
//         ntn: "9876543-2",
//         contact_person: "Saad Ahmed",
//         email: "admin@bluepeak.example",
//         services_enabled: { shuttle_enabled: false, chauffeur_enabled: true },
//         allowed_vehicle_models: ["Civic", "City"],
//         employees: [],
//         created_at: now,
//       },
//     ],
//   };
// }


